### PR TITLE
Finish the move of ns3 launch script and fix systemd path

### PR DESCRIPTION
**Pull request by ntonnaett**

### CODE REVIEW

**Comment by antonroman** [comment]
Hi Nils,

first of all, thank you very much for contributing :-) 
I'd just like to know why the it's needed to use `/usr/lib/systemd/system` instead of `/etc/systemd/system`. Please, it is just for my own curiosity, since you have found some problem with the previous path I will gladly approve the merge. 

Thanks in advance for your time and contributing!. 

Note: According to this link I don't completely understand why we should use the `/usr/lib` path: [What's the difference between /usr/lib/systemd/system and /etc/systemd/system?](https://unix.stackexchange.com/questions/206315/whats-the-difference-between-usr-lib-systemd-system-and-etc-systemd-system )

**Comment by ntonnaett** [comment]
`/usr/lib/systemd/system` is the directory where packages, projects etc. put their service files. `/etc/systemd/system` is where administrator put their service files manually. It's just a (quiet bad) split between files the administrator can modify and the files packages might be overriding. Enabling a service puts a symlink in `/etc/systemd/system` to the corresponding file that the package installed. Systemd's documentation is just bad and the split is not clean at all. There should be three directories in my opinion.

**Comment by antonroman** [comment]
Ok,

understood, thanks!

**Comment by ntonnaett** [comment]
I'm just realizing that the split between `/usr` for things installed by the distribution and `/usr/local` for things that are installed manually _is_ done in systemd: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path
So the correct path would actually be `/usr/local/lib/systemd/system` for us. If there would be a ns3 service provided by a distribution package, they won't override each other.

**Pull request merged**
